#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ButtonClicker.Resource", IsApplication=true)]

namespace ButtonClicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int AccentColor = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int BlurbColor = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int ButtonTextColor = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int PopupColor = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int PopupTextColor = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int SignOutButtonBackground = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int SignOutButtonTextColor = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_dark = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_light_pressed = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int TitleSize = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_height = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int adjust_width = 2131361799;
			
			// aapt resource value: 0x7f0a0003
			public const int auto = 2131361795;
			
			// aapt resource value: 0x7f0a0014
			public const int button_accept_popup_invitation = 2131361812;
			
			// aapt resource value: 0x7f0a0019
			public const int button_click_me = 2131361817;
			
			// aapt resource value: 0x7f0a000f
			public const int button_invite_players = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int button_quick_game = 2131361806;
			
			// aapt resource value: 0x7f0a0010
			public const int button_see_invitations = 2131361808;
			
			// aapt resource value: 0x7f0a000b
			public const int button_sign_in = 2131361803;
			
			// aapt resource value: 0x7f0a0011
			public const int button_sign_out = 2131361809;
			
			// aapt resource value: 0x7f0a000a
			public const int button_single_player = 2131361802;
			
			// aapt resource value: 0x7f0a000d
			public const int button_single_player_2 = 2131361805;
			
			// aapt resource value: 0x7f0a001a
			public const int countdown = 2131361818;
			
			// aapt resource value: 0x7f0a0004
			public const int dark = 2131361796;
			
			// aapt resource value: 0x7f0a0000
			public const int icon_only = 2131361792;
			
			// aapt resource value: 0x7f0a0013
			public const int incoming_invitation_text = 2131361811;
			
			// aapt resource value: 0x7f0a0017
			public const int instructions = 2131361815;
			
			// aapt resource value: 0x7f0a0012
			public const int invitation_popup = 2131361810;
			
			// aapt resource value: 0x7f0a0005
			public const int light = 2131361797;
			
			// aapt resource value: 0x7f0a0018
			public const int my_score = 2131361816;
			
			// aapt resource value: 0x7f0a0008
			public const int none = 2131361800;
			
			// aapt resource value: 0x7f0a001b
			public const int score0 = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int score1 = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int score2 = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int score3 = 2131361822;
			
			// aapt resource value: 0x7f0a0016
			public const int screen_game = 2131361814;
			
			// aapt resource value: 0x7f0a000c
			public const int screen_main = 2131361804;
			
			// aapt resource value: 0x7f0a0009
			public const int screen_sign_in = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int screen_wait = 2131361813;
			
			// aapt resource value: 0x7f0a0001
			public const int standard = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int wide = 2131361794;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060022
			public const int accept_popup_invite = 2131099682;
			
			// aapt resource value: 0x7f060014
			public const int app_id = 2131099668;
			
			// aapt resource value: 0x7f06002b
			public const int app_misconfigured = 2131099691;
			
			// aapt resource value: 0x7f060015
			public const int app_name = 2131099669;
			
			// aapt resource value: 0x7f060027
			public const int click_me = 2131099687;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_enable_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_title = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_text_phone = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text_tablet = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_notification_ticker = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_unknown_issue = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_unsupported_text = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_unsupported_title = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_button = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_text = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_title = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_updating_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_updating_title = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_wear_update_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_open_on_phone = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int common_signin_button_text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text_long = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int game_blurb = 2131099672;
			
			// aapt resource value: 0x7f060026
			public const int game_problem = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int game_title = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int hello = 2131099670;
			
			// aapt resource value: 0x7f060025
			public const int instructions = 2131099685;
			
			// aapt resource value: 0x7f060021
			public const int inv_popup_text = 2131099681;
			
			// aapt resource value: 0x7f06001c
			public const int invite_players = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int invite_players_explanation = 2131099679;
			
			// aapt resource value: 0x7f060028
			public const int is_inviting_you = 2131099688;
			
			// aapt resource value: 0x7f06002c
			public const int license_failed = 2131099692;
			
			// aapt resource value: 0x7f060024
			public const int please_wait = 2131099684;
			
			// aapt resource value: 0x7f06001b
			public const int quick_game = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int quick_game_explanation = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int see_invitations = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int see_invitations_explanation = 2131099680;
			
			// aapt resource value: 0x7f06002a
			public const int sign_in_failed = 2131099690;
			
			// aapt resource value: 0x7f060023
			public const int sign_out = 2131099683;
			
			// aapt resource value: 0x7f060029
			public const int signin_other_error = 2131099689;
			
			// aapt resource value: 0x7f060019
			public const int single_player = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int single_player_explanation = 2131099674;
			
			// aapt resource value: 0x7f06002d
			public const int unknown_error = 2131099693;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int Blurb = 2131296262;
			
			// aapt resource value: 0x7f090013
			public const int ButtonsBox = 2131296275;
			
			// aapt resource value: 0x7f090010
			public const int FigureLabel = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int FigureView = 2131296271;
			
			// aapt resource value: 0x7f090007
			public const int GameBlurb = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int GameButton = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int GameScreen = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int GameTitle = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int GameplayScreen = 2131296259;
			
			// aapt resource value: 0x7f090015
			public const int Instructions = 2131296277;
			
			// aapt resource value: 0x7f090004
			public const int InvPopup = 2131296260;
			
			// aapt resource value: 0x7f09000d
			public const int InvPopupButton = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int InvPopupText = 2131296268;
			
			// aapt resource value: 0x7f090002
			public const int LLScreen = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int MainScreenButton = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int MainScreenButtonBlurb = 2131296267;
			
			// aapt resource value: 0x7f090018
			public const int PlacementDisplay = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int ScoreDisplay = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int ScoreLabel = 2131296278;
			
			// aapt resource value: 0x7f090014
			public const int ScoreText = 2131296276;
			
			// aapt resource value: 0x7f090011
			public const int ScoreToast = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int ScoresBox = 2131296274;
			
			// aapt resource value: 0x7f090019
			public const int SectionLabel = 2131296281;
			
			// aapt resource value: 0x7f090008
			public const int SignInButton = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int SignOutButton = 2131296270;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
